"""empty message

Revision ID: 2e8daef153c6
Revises: 
Create Date: 2025-02-20 17:34:15.679336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e8daef153c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comprador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('direccion_envio', sa.String(), nullable=False),
    sa.Column('historial_compras', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vendedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('reputation', sa.String(), nullable=False),
    sa.Column('historial_ventas', sa.String(), nullable=False),
    sa.Column('productos_en_venta', sa.String(), nullable=False),
    sa.Column('publicar_producto', sa.String(), nullable=False),
    sa.Column('ingresos_totales', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'completado', 'cancelado', name='estado'), nullable=False),
    sa.Column('fecha_compra', sa.DateTime(), nullable=False),
    sa.Column('payment_options', sa.String(length=80), nullable=False),
    sa.Column('comprador_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comprador_id'], ['comprador.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('fecha_publicacion', sa.DateTime(), nullable=False),
    sa.Column('direccion_envio', sa.String(), nullable=False),
    sa.Column('size', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('peso', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('final_price', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('tipo1', 'tipo2', 'tipo3', name='category'), nullable=False),
    sa.Column('vendedor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vendedor_id'], ['vendedor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('is_rol', sa.Boolean(), nullable=False),
    sa.Column('comprador_id', sa.Integer(), nullable=True),
    sa.Column('vendedor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comprador_id'], ['comprador.id'], ),
    sa.ForeignKeyConstraint(['vendedor_id'], ['vendedor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_Amount', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('fecha_Llegada', sa.DateTime(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_item')
    op.drop_table('usuario')
    op.drop_table('producto')
    op.drop_table('orders')
    op.drop_table('vendedor')
    op.drop_table('comprador')
    # ### end Alembic commands ###
