"""empty message

Revision ID: 30290c764852
Revises: 58c565b1a277
Create Date: 2025-09-26 18:20:48.448458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30290c764852'
down_revision = '58c565b1a277'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comida', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ts_init', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comida', schema=None) as batch_op:
        batch_op.drop_column('ts_init')

    # ### end Alembic commands ###
