"""empty message

Revision ID: 67a9e6e6e8fb
Revises: b4c7edb2f599
Create Date: 2026-04-10 08:10:48.397700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67a9e6e6e8fb'
down_revision = 'b4c7edb2f599'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis', schema=None) as batch_op:
        batch_op.alter_column('foto_analysis',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('comida', schema=None) as batch_op:
        batch_op.alter_column('foto_food',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('incidencias', schema=None) as batch_op:
        batch_op.alter_column('foto_incidencia',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('mascotas', schema=None) as batch_op:
        batch_op.alter_column('foto_mascot',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mascotas', schema=None) as batch_op:
        batch_op.alter_column('foto_mascot',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('incidencias', schema=None) as batch_op:
        batch_op.alter_column('foto_incidencia',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('comida', schema=None) as batch_op:
        batch_op.alter_column('foto_food',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('analysis', schema=None) as batch_op:
        batch_op.alter_column('foto_analysis',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
