"""empty message

Revision ID: be7f83f3d0e1
Revises: 30290c764852
Create Date: 2025-10-05 16:58:09.937418

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'be7f83f3d0e1'
down_revision = '30290c764852'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reportes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('future_ia', sa.Text(), nullable=False))
        batch_op.alter_column('ts_alta',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('veterinarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_colegiado', sa.String(), nullable=True))
        batch_op.create_unique_constraint(None, ['num_colegiado'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veterinarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('num_colegiado')

    with op.batch_alter_table('reportes', schema=None) as batch_op:
        batch_op.alter_column('ts_alta',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_column('future_ia')

    # ### end Alembic commands ###
